# Generated by Django 2.0.3 on 2018-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('ssh_port', models.PositiveIntegerField()),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(max_length=32)),
                ('project', models.CharField(choices=[(1, '开发'), (2, '运维'), (3, '测试')], default=3, max_length=32)),
                ('option', models.CharField(choices=[(1, '生产'), (2, '测试')], default=2, max_length=32)),
                ('status', models.CharField(choices=[(1, '使用中'), (2, '闲置'), (3, '损坏')], default=2, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
